// Generated by LiveScript 1.5.0
(function(){
  var games, util, choose, command, controller, execute, using, safely, txt, out$ = typeof exports != 'undefined' && exports || this;
  games = require('./games');
  util = require('./util');
  choose = util.fromRandom;
  command = /\s*(\S+)\s*(.+)?/;
  controller = {
    say: function(it){
      return it + "";
    },
    flip: function(){
      return choose(['heads', 'tails']);
    },
    roll: function(){
      return '' + util.upTo(1000000);
    },
    ask: function(){
      return util.fromRandom(games.questions);
    },
    tell: function(){
      return util.fromRandom(games.answers);
    }
  };
  execute = function(command, content){
    if (controller.hasOwnProperty(command)) {
      return controller[command](content);
    }
  };
  using = function(message){
    var that;
    if (that = message.match(command)) {
      return execute(that[1], that[2]);
    }
  };
  safely = function(content){
    return content || 'I have nothing to say.';
  };
  txt = function(it){
    return it.reply(safely(using(it.body)));
  };
  out$.txt = txt;
  out$.safely = safely;
  out$.using = using;
  out$.execute = execute;
  out$.controller = controller;
  out$.command = command;
}).call(this);
