// Generated by CoffeeScript 1.10.0
var chai, expect;

chai = require('chai');

expect = chai.expect;

describe('Array', function() {
  return describe('#indexOf()', function() {
    return it('should return -1 when the value is not present', function() {
      var sampleArray;
      sampleArray = ['a', 'b', 'c'];
      expect(sampleArray).not.to.include.members(['d']);
      return expect(sampleArray.indexOf('d')).to.equal(-1);
    });
  });
});
