  // Generated by CoffeeScript 1.10.0
  var asCommand, classifier, natural, readline, rl, spellcheck, tokenizer, wordnet, wordpos, wp;

  readline = require('readline');

  natural = require('natural');

  wp = require('wordpos');

  wordpos = new wp();

  tokenizer = new natural.WordTokenizer();

  wordnet = new natural.WordNet();

  classifier = new natural.BayesClassifier();

  spellcheck = new natural.Spellcheck();

  natural.LancasterStemmer.attach();

  classifier.addDocument('What does amortize mean?', 'define');

  classifier.addDocument('What\'s another word for amortize?', 'synonym');

  classifier.addDocument('short gold', 'sell');

  classifier.addDocument('sell gold', 'sell');

  classifier.train();

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  asCommand = function(answer) {
    var tokens, word;
    tokens = tokenizer.tokenize(answer);
    word = tokens.shift();
    tokenizer.tokenize(word).forEach(function(word) {
      return wordnet.lookup(word, function(results) {
        return console.log(results[0]);
      });
    });
    return rl.close();
  };

  rl.question('wyrz> ', asCommand);
